os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.9.4"
jdk:
  - oraclejdk8
cache:
  directories:
    - node_modules
    - $HOME/.m2
env:
  global:
    - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
    - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
    - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
    - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
  matrix:
    - JHIPSTER=app-3.7.1
    - JHIPSTER=app-2.27.2
install:
  - $JHIPSTER_INSTALL/01-install-jhipster-swagger-cli-stack.sh
  - $JHIPSTER_INSTALL/02-checkVersion.sh
script:
  - $JHIPSTER_SCRIPTS/01-generate-project.sh
  - $JHIPSTER_SCRIPTS/02-tests.sh
